### ISSUE TITLE
brenan_WT.fasta

### ISSUE THREAD

**Issue by EasyPiPi** [mat10d/EvolvePro#8]
Dear author,

It's very exciting to see your paper is published and we're highly interested in trying your method. I have two technical questions:

(1) I went through the tutorial and found several places that require brenan_WT.fasta as input. I assume it's a protein sequence like dataset_WT.fasta or kelsic_WT.fasta, right? Is it the protein sequence of the gene MAPK1?

(2) I also noticed you recommend running the method on HPC. Do you have an estimate on how much computational resources are needed in practice? For example, for a typical protein with 400 aa, will an HPC with A100 and 2TB RAM do the job? Alternatively, if we only have a desktop with GTX3060 or GTX4090 and 128GB RAM, how long of a peptide may be taken care of? I understand sometimes it's very hard to answer this kind of question, but a rough guess based on your experience will help us a lot to determine if we can do it or not in the lab.

Many thanks,
Yixin

**Comment by GitHUB-ZYD** [comment]
>WT Wild-type sequence
MAAAAAAGAGPEMVRGQVFDVGPRYTNLSYIGEGAYGMVCSAYDNVNKVRVAIKKISPFE
HQTYCQRTLREIKILLRFRHENIIGINDIIRAPTIEQMKDVYIVQDLMETDLYKLLKTQH
LSNDHICYFLYQILRGLKYIHSANVLHRDLKPSNLLLNTTCDLKICDFGLARVADPDHDH
TGFLTEYVATRWYRAPEIMLNSKGYTKSIDIWSVGCILAEMLSNRPIFPGKHYLDQLNHI
LGILGSPSQEDLNCIINLKARNYLLSLPHKNKVPWNRLFPNADSKALDLLDKMLTFNPHK
RIEVEQALAHPYLEQYYDPSDEPIAEAPFKFDMELDDLPKEKLKELIFEETARFQPGYRS

**Comment by mat10d** [comment]
Thanks for raising this! I added the WT fasta files in [this](https://github.com/mat10d/EvolvePro/commit/9cec676c031bac5dc6b5301383d09e9d1ee8fb37) commit. Yes, the brenan dataset is a MAPK1 DMS paper.

Running on an HPC is only really necessary to get embeddings. So if you are getting esm2 embeddings, I would refer to their [repository](https://github.com/facebookresearch/esm) on how to do this outside an HPC. We use a small model for the colab example because that is all we can get away with on limited RAM provided. Evolvepro itself is super lightweight and doesn't require an HPC. The DMS experiments were conducted on HPCs because they take time to run, and we have an HPC available to submit these jobs to.
